version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - inner
    depends_on:
      - db
      - api-migrations

  api-migrations:
    container_name: api-migrations
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: diesel
    volumes:
      - ./:/app
    networks:
      - inner
    depends_on:
      - db

  db:
    container_name: apidb
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - inner

networks:
  inner:


volumes:
  db:
    name: rest-api-db
