version: '3.9'

services:
  api:
    image: thegriglat/rust-actix-api-example
    container_name: rust-actix-api-example
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: rust-actix-api-example
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - inner
    depends_on:
      - db
      - api-migrations

  api-migrations:
    image: thegriglat/rust-actix-api-example-migrations
    container_name: rust-actix-api-example-migrations
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: rust-actix-api-example-migrations
    volumes:
      - ./:/app
    networks:
      - inner
    depends_on:
      - db

  db:
    container_name: rust-actix-api-example-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - inner

networks:
  inner:


volumes:
  db:
    name: rust-actix-api-example-db
