version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - db:/db/
    networks:
      - inner
    depends_on:
      - api-migrations

  api-migrations:
    container_name: api-migrations
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: api-migrations
    volumes:
      - db:/db/
    env_file:
      - .env
    networks:
      - inner

networks:
  inner:


volumes:
  db:
